# Generated by Django 5.0.7 on 2024-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Songs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.TextField()),
                ("uri", models.TextField()),
                ("name", models.TextField()),
                ("artist", models.TextField()),
                ("explicit", models.TextField()),
                ("genres", models.TextField()),
                ("danceability", models.FloatField()),
                ("energy", models.FloatField()),
                ("key", models.IntegerField()),
                ("loudness", models.FloatField()),
                ("speechiness", models.FloatField()),
                ("acoustics", models.FloatField()),
                ("instrumentalness", models.FloatField()),
                ("liveliness", models.FloatField()),
                ("valence", models.FloatField()),
                ("tempo", models.FloatField()),
                ("duration_seconds", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="userInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
